# Generated by Django 5.0 on 2023-12-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_chat_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='genaiSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperture', models.FloatField(default=0.99)),
                ('max_length', models.IntegerField(default=1000)),
                ('top_p', models.FloatField(default=0.9)),
                ('top_k', models.IntegerField(default=0)),
                ('num_return_sequences', models.IntegerField(default=1)),
                ('repetition_penalty', models.FloatField(default=1.0)),
                ('length_penalty', models.FloatField(default=1.0)),
                ('do_sample', models.BooleanField(default=True)),
                ('early_stopping', models.BooleanField(default=True)),
                ('num_beams', models.IntegerField(default=1)),
            ],
        ),
    ]
