# Generated by Django 5.0 on 2023-12-24 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_chat_bot', '0002_genaisetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='genaisetting',
            name='do_sample',
        ),
        migrations.RemoveField(
            model_name='genaisetting',
            name='early_stopping',
        ),
        migrations.RemoveField(
            model_name='genaisetting',
            name='length_penalty',
        ),
        migrations.RemoveField(
            model_name='genaisetting',
            name='num_beams',
        ),
        migrations.RemoveField(
            model_name='genaisetting',
            name='num_return_sequences',
        ),
        migrations.RemoveField(
            model_name='genaisetting',
            name='repetition_penalty',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='response',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='conversation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_chat_bot.conversation'),
            preserve_default=False,
        ),
    ]
