# Generated by Django 5.0 on 2023-12-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_chat_bot', '0003_conversation_remove_genaisetting_do_sample_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
