# Generated by Django 5.0 on 2023-12-24 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_chat_bot', '0004_conversation_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_chat_bot.conversation'),
        ),
    ]
