name: Update README with Screenshot

on:
  workflow_run:
    workflows: ["Build and Deploy"]
    types:
      - completed

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload Screenshot
        uses: actions/upload-artifact@v2
        with:
          name: screenshot
          path: screenshot.png

