name: Update README with Screenshots

on:
  workflow_run:
    workflows: ["Build and Deploy"]
    types:
      - completed

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload Screenshots
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: .

      - name: Update README
        run: |
          echo "![Ekran Resmi 1](screenshot1.png)" >> README.md
          echo "![Ekran Resmi 2](screenshot2.png)" >> README.md

